version: '3.7'

services:
  drupal:
    image: docker.io/osuwams/drupal:8-apache-dev
    environment:
      - DRUPAL_DBHOST=database
      - DRUPAL_DBUSER=drupal
      - DRUPAL_DBPASS=drupal
      - DRUPAL_DBNAME=drupal
      - DRUPAL_THEME_DEVEL=true
    ports:
      - 8080:80
    volumes:
      - drupal-files:/var/www/html/docroot/sites/default/files
      - ./:/var/www/html/docroot/themes/custom/madrone
    restart: unless-stopped
  database:
    image: docker.io/library/mariadb:10.4
    volumes:
      - drupal-db:/var/lib/mysql/drupal
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: unless-stopped

volumes:
  drupal-db:
  drupal-files:
