name: Drupal coding standards

on:
  pull_request:
    branches: [ 1.x ]
jobs:
  phpcs-drupal:
    name: Drupal coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guix77/phpcs-drupal-action@v1.0.1
      - uses: DirtDiglett/actions-twigcs@1.0.0
